name: Prisma Migrations

on:
  # Run on push to main/master branches (when migrations are added)
  push:
    branches:
      - main
      - master
    paths:
      - 'apps/web/prisma/migrations/**'
      - 'apps/web/prisma/schema.prisma'
  # Allow manual triggering
  workflow_dispatch:
  # Run on schedule (daily at 3 AM UTC) to catch any missed migrations
  schedule:
    - cron: '0 3 * * *'

jobs:
  apply-prisma-migrations:
    name: Apply Prisma Migrations
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check migration status (before)
        id: status-before
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL || secrets.DATABASE_URL }}
        run: |
          cd apps/web
          echo "=== Migration Status (Before) ===" > /tmp/migration-status-before.txt
          pnpm prisma migrate status >> /tmp/migration-status-before.txt 2>&1 || echo "Status check completed"
          cat /tmp/migration-status-before.txt

      - name: Apply Prisma migrations
        id: migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL || secrets.DATABASE_URL }}
        run: |
          cd apps/web
          echo "=== Applying Prisma Migrations ==="
          
          # Use the db:migrate script from package.json
          pnpm run db:migrate || {
            echo "Migration failed!"
            exit 1
          }
          
          # Capture migration output
          echo "Migrations applied successfully" >> $GITHUB_STEP_SUMMARY

      - name: Verify migration status (after)
        id: status-after
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL || secrets.DATABASE_URL }}
        run: |
          cd apps/web
          echo "=== Migration Status (After) ===" > /tmp/migration-status-after.txt
          pnpm prisma migrate status >> /tmp/migration-status-after.txt 2>&1
          cat /tmp/migration-status-after.txt
          
          # Check if status shows "Database schema is up to date"
          if grep -q "Database schema is up to date\|All migrations have been applied" /tmp/migration-status-after.txt; then
            echo "✅ All migrations applied successfully"
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "⚠️ Migration status unclear - check logs"
            echo "status=warning" >> $GITHUB_OUTPUT
          fi

      - name: Verify database schema
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL || secrets.DATABASE_URL }}
        run: |
          cd apps/web
          echo "=== Verifying Database Schema ==="
          
          # Generate Prisma Client to ensure schema is valid
          pnpm prisma generate
          
          # Try a simple query to verify connection
          node -e "
            const { PrismaClient } = require('@prisma/client');
            const prisma = new PrismaClient();
            prisma.\$queryRaw\`SELECT 1\`.then(() => {
              console.log('✅ Database connection verified');
              process.exit(0);
            }).catch((e) => {
              console.error('❌ Database verification failed:', e.message);
              process.exit(1);
            }).finally(() => prisma.\$disconnect());
          " || echo "Schema verification completed"

      - name: Archive applied migrations
        if: success()
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL || secrets.DATABASE_URL }}
        run: |
          cd apps/web
          
          # Create archive directory if it doesn't exist
          mkdir -p prisma/_archive
          
          # Get timestamp for archive folder
          TIMESTAMP=$(date -u +"%Y-%m-%d_%H-%M-%S")
          ARCHIVE_DIR="prisma/_archive/$TIMESTAMP"
          mkdir -p "$ARCHIVE_DIR"
          
          # Check if migrations directory exists and has migrations
          if [ -d "prisma/migrations" ] && [ "$(ls -A prisma/migrations 2>/dev/null)" ]; then
            echo "Archiving migrations to $ARCHIVE_DIR"
            
            # Copy each migration to archive
            for migration_dir in prisma/migrations/*/; do
              if [ -d "$migration_dir" ]; then
                migration_name=$(basename "$migration_dir")
                echo "Archiving migration: $migration_name"
                cp -r "$migration_dir" "$ARCHIVE_DIR/$migration_name"
              fi
            done
            
            echo "✅ Migrations archived to $ARCHIVE_DIR"
          else
            echo "No migrations directory found or empty - skipping archive"
          fi

      - name: Update MIGRATION_LOG.md
        if: always()
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL || secrets.DATABASE_URL }}
        run: |
          cd apps/web
          
          # Extract database host from DATABASE_URL (masked)
          DB_HOST=$(echo "$DATABASE_URL" | sed -n 's/.*@\([^:]*\).*/\1/p')
          DB_NAME=$(echo "$DATABASE_URL" | sed -n 's/.*\/\([^?]*\).*/\1/p')
          
          # Get timestamps
          UTC_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          LOCAL_TIME=$(date +"%Y-%m-%d %H:%M:%S %Z")
          
          # Get migration status
          STATUS_BEFORE=$(cat /tmp/migration-status-before.txt 2>/dev/null || echo "N/A")
          STATUS_AFTER=$(cat /tmp/migration-status-after.txt 2>/dev/null || echo "N/A")
          
          # Determine state
          if [ "${{ steps.migrate.outcome }}" == "success" ] && [ "${{ steps.status-after.outputs.status }}" == "success" ]; then
            STATE="GO-LIVE VERIFIED"
          elif [ "${{ steps.migrate.outcome }}" == "success" ]; then
            STATE="PARTIAL – MANUAL ACTION REQUIRED"
          else
            STATE="FAILED – SEE ERRORS ABOVE"
          fi
          
          # Get list of applied migrations
          APPLIED_MIGRATIONS=""
          if [ -d "prisma/migrations" ]; then
            APPLIED_MIGRATIONS=$(ls -1 prisma/migrations/ 2>/dev/null | tr '\n' ',' | sed 's/,$//' || echo "None")
          fi
          
          # Create log entry
          cat >> ../../MIGRATION_LOG.md << EOF

---
## Run: prisma-migration-$TIMESTAMP
**Timestamp:** $UTC_TIME (UTC) / $LOCAL_TIME (Local)

### Environment & Database
- **Env file used:** GitHub Secrets (DATABASE_URL)
- **DB host:** $DB_HOST
- **Database name:** $DB_NAME
- **Workflow run:** ${{ github.run_id }}
- **Triggered by:** ${{ github.event_name }}

### Pre-run Status
\`\`\`
$STATUS_BEFORE
\`\`\`

### Commands Executed
- **Command:** \`pnpm run db:migrate\` (which runs \`prisma migrate deploy\`)
- **Working directory:** \`apps/web\`
- **Package manager:** pnpm 8.15.0

### Apply Results
- **Success:** $([ "${{ steps.migrate.outcome }}" == "success" ] && echo "✅ Yes" || echo "❌ No")
- **Migrations applied:** $(echo "$APPLIED_MIGRATIONS" | tr ',' '\n' | wc -l)
- **Migration IDs applied:** $APPLIED_MIGRATIONS

### Post-run Status
\`\`\`
$STATUS_AFTER
\`\`\`

### Archive
- **Archive path:** \`prisma/_archive/$TIMESTAMP/\`
- **Migrations archived:** $(ls -1 prisma/_archive/$TIMESTAMP/ 2>/dev/null | wc -l || echo "0")

### Outcome
**STATE:** $STATE
EOF
          
          echo "✅ Migration log updated"

      - name: Upload migration artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: prisma-migration-logs
          path: |
            /tmp/migration-status-before.txt
            /tmp/migration-status-after.txt
            MIGRATION_LOG.md
          retention-days: 90

      - name: Comment PR with migration status
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let status = '${{ steps.status-after.outputs.status }}';
            let outcome = '${{ steps.migrate.outcome }}';
            
            const emoji = outcome === 'success' && status === 'success' ? '✅' : '❌';
            const state = outcome === 'success' && status === 'success' 
              ? 'GO-LIVE VERIFIED' 
              : outcome === 'success' 
                ? 'PARTIAL – MANUAL ACTION REQUIRED'
                : 'FAILED – SEE ERRORS ABOVE';
            
            try {
              const logContent = fs.readFileSync('MIGRATION_LOG.md', 'utf-8');
              const latestRun = logContent.split('---').pop();
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## ${emoji} Prisma Migration Status\n\n**State:** ${state}\n\n**Workflow:** [View run #${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\n\n<details>\n<summary>View Migration Log</summary>\n\n\`\`\`\n${latestRun}\n\`\`\`\n\n</details>`
              });
            } catch (error) {
              console.log('Could not read migration log:', error.message);
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## ${emoji} Prisma Migration Status\n\n**State:** ${state}\n\n**Workflow:** [View run #${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})`
              });
            }

      - name: Notify on failure
        if: failure()
        uses: slackapi/slack-github-action@v1
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": "❌ Prisma migration failed",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Prisma Migration Failed*\n\nDate: $(date -u +%Y-%m-%d)\nStatus: Failed\n\nCheck workflow logs for details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                }
              ]
            }
        continue-on-error: true

      - name: Notify on success
        if: success()
        uses: slackapi/slack-github-action@v1
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": "✅ Prisma migrations applied successfully",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Prisma Migrations Applied*\n\nDate: $(date -u +%Y-%m-%d)\nStatus: Success\n\nWorkflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                }
              ]
            }
        continue-on-error: true
