-- ============================================================================
-- CONSOLIDATED REMAINDER MIGRATION
-- Generated by Gemini 3 (AIAS Audit)
-- Date: 2026-01-07
-- Purpose: Align DB Schema with Application (Prisma) and Supabase Systems
-- Focus: DDL-First, Idempotent, No Duplicates
-- ============================================================================

-- 1. EXTENSIONS
-- ============================================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "vector"; -- Assumed for AI features

-- 2. HELPER FUNCTIONS
-- ============================================================================
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 3. CORE TENANCY (SUPABASE NATIVE)
-- Used by: Agents, Workflows, Edge Functions
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.tenants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- RLS for tenants
ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;

-- 4. CORE TENANCY (PRISMA / APP LEGACY)
-- Used by: Next.js App, Stripe, Billing
-- NOTICE: This creates a parallel structure due to CUID vs UUID mismatch in codebase.
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.organizations (
    id TEXT PRIMARY KEY, -- CUID from Prisma
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    logo TEXT,
    website TEXT,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- RLS for organizations
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;

-- 5. USERS (PUBLIC PROFILE)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.users (
    id TEXT PRIMARY KEY, -- CUID
    email TEXT UNIQUE NOT NULL,
    name TEXT,
    avatar TEXT,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "supabaseId" TEXT UNIQUE -- Link to auth.users
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- 6. MEMBERSHIPS (SUPABASE NATIVE)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.tenant_members (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    role VARCHAR(50) NOT NULL DEFAULT 'viewer',
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(tenant_id, user_id)
);

ALTER TABLE public.tenant_members ENABLE ROW LEVEL SECURITY;

-- 7. MEMBERSHIPS (PRISMA / APP LEGACY)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.memberships (
    id TEXT PRIMARY KEY, -- CUID
    role TEXT NOT NULL DEFAULT 'VIEWER',
    "userId" TEXT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    "orgId" TEXT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    UNIQUE("userId", "orgId")
);

ALTER TABLE public.memberships ENABLE ROW LEVEL SECURITY;

-- 8. CORE SYSTEM TABLES (Ensure existence for Agents/Workflows)
-- Referencing 'tenants' (UUID)
-- ============================================================================

-- Agents
CREATE TABLE IF NOT EXISTS public.agents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(200) NOT NULL,
  description TEXT,
  version VARCHAR(20) NOT NULL,
  category VARCHAR(50) NOT NULL,
  planning_style VARCHAR(50) NOT NULL DEFAULT 'sequential',
  capabilities JSONB NOT NULL DEFAULT '{}',
  tools JSONB NOT NULL DEFAULT '[]',
  execution_config JSONB NOT NULL DEFAULT '{}',
  memory_config JSONB DEFAULT NULL,
  safety_constraints JSONB NOT NULL DEFAULT '{}',
  validation_schema JSONB DEFAULT NULL,
  output_type VARCHAR(50) NOT NULL,
  output_schema JSONB DEFAULT NULL,
  enabled BOOLEAN NOT NULL DEFAULT true,
  deprecated BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID REFERENCES auth.users(id),
  tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE
);
ALTER TABLE public.agents ENABLE ROW LEVEL SECURITY;

-- Workflows
CREATE TABLE IF NOT EXISTS public.workflows (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(200) NOT NULL,
  description TEXT,
  version VARCHAR(20) NOT NULL,
  trigger JSONB NOT NULL,
  steps JSONB NOT NULL DEFAULT '[]',
  start_step_id UUID NOT NULL,
  category VARCHAR(50) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID REFERENCES auth.users(id),
  tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE
);
ALTER TABLE public.workflows ENABLE ROW LEVEL SECURITY;

-- 9. MINIMAL RLS POLICIES (No Spam, No Overlaps)
-- ============================================================================

-- Tenants: Users can view tenants they are members of
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'tenants' AND policyname = 'Members can view tenants') THEN
    CREATE POLICY "Members can view tenants" ON public.tenants
    FOR SELECT USING (
      id IN (SELECT tenant_id FROM public.tenant_members WHERE user_id = auth.uid() AND status = 'active')
    );
  END IF;
END $$;

-- Organizations: Users can view organizations they are members of (Prisma style)
-- Note: This requires linking auth.uid() (UUID) to users.supabaseId (Text) or users.id (Text)
-- Complex join required.
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'organizations' AND policyname = 'Members can view organizations') THEN
    CREATE POLICY "Members can view organizations" ON public.organizations
    FOR SELECT USING (
      id IN (
        SELECT "orgId" FROM public.memberships m
        JOIN public.users u ON m."userId" = u.id
        WHERE u."supabaseId" = auth.uid()::text
      )
    );
  END IF;
END $$;

-- 10. INDEXES (Prevent Duplicates)
-- ============================================================================
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_tenant_members_user_id') THEN
    CREATE INDEX idx_tenant_members_user_id ON public.tenant_members(user_id);
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_memberships_userId') THEN
    CREATE INDEX "idx_memberships_userId" ON public.memberships("userId");
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_users_supabaseId') THEN
    CREATE INDEX "idx_users_supabaseId" ON public.users("supabaseId");
  END IF;
END $$;

-- 11. TRIGGERS (Idempotent)
-- ============================================================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.triggers WHERE trigger_name = 'update_tenants_updated_at') THEN
    CREATE TRIGGER update_tenants_updated_at BEFORE UPDATE ON public.tenants
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  END IF;
END $$;
